version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      # KAFKA_BROKER_ID: 1
      # KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  producer:
    build: 
      context: .
      dockerfile: docker/Dockerfile.producer
    container_name: sentiment-producer
    depends_on:
      - broker
    volumes:
      - .:/app
    restart: always

  consumer:
    build: 
      context: .
      dockerfile: docker/Dockerfile.consumer
    container_name: sentiment-consumer
    depends_on:
      - broker
    volumes:
      - .:/app
      - ./shared_data:/app/shared_data
    restart: always

  dashboard:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dashboard
    container_name: sentiment-dashboard
    depends_on:
      - consumer
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./shared_data:/app/shared_data
    restart: always